server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jwdevelopper/repo-teste
          username: jwjunior
          password: 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
          default-label: main
          search-paths:
            - 'greeting-service*'