server:
  port: ${PORT:0}
spring:
  application:
    name: book-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/book_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
  flyway:
    baseline-on-migrate: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
