server:
  port: ${PORT:0}
spring:
  application:
    name: book-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/book_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
  flyway:
    baseline-on-migrate: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        #enable-exponential-backoff: true
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10


#      pode ter quantos quiser desde que mude o nome
#      default:
#        max-attempts: 5
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
        #include: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true